// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVt-To0Yvk_ERGIuaNCwY2cLmHgPiZL6U',
    appId: '1:41797673188:web:bff3ab98e203577456ccf1',
    messagingSenderId: '41797673188',
    projectId: 'last-5fe00',
    authDomain: 'last-5fe00.firebaseapp.com',
    storageBucket: 'last-5fe00.firebasestorage.app',
    measurementId: 'G-WBJ1G2LR62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVdtuYapgBI-CCIkri-GUipmOEzGXlUa8',
    appId: '1:41797673188:android:1dfd3f7026f7615b56ccf1',
    messagingSenderId: '41797673188',
    projectId: 'last-5fe00',
    storageBucket: 'last-5fe00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3RxKAg7syh2GOg0C1aczPLpbtQZR9maY',
    appId: '1:41797673188:ios:519513291f16b6fc56ccf1',
    messagingSenderId: '41797673188',
    projectId: 'last-5fe00',
    storageBucket: 'last-5fe00.firebasestorage.app',
    iosBundleId: 'com.example.last',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3RxKAg7syh2GOg0C1aczPLpbtQZR9maY',
    appId: '1:41797673188:ios:519513291f16b6fc56ccf1',
    messagingSenderId: '41797673188',
    projectId: 'last-5fe00',
    storageBucket: 'last-5fe00.firebasestorage.app',
    iosBundleId: 'com.example.last',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVt-To0Yvk_ERGIuaNCwY2cLmHgPiZL6U',
    appId: '1:41797673188:web:06f121488edf3e2156ccf1',
    messagingSenderId: '41797673188',
    projectId: 'last-5fe00',
    authDomain: 'last-5fe00.firebaseapp.com',
    storageBucket: 'last-5fe00.firebasestorage.app',
    measurementId: 'G-87GRX82C30',
  );
}
